# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_lecture_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('value', models.PositiveIntegerField(default=0)),
                ('answer', models.CharField(default=None, max_length=500)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Lecture')),
            ],
        ),
    ]
