# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20170320_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('textanswer', models.CharField(max_length=500)),
                ('option1', models.CharField(max_length=500)),
                ('option2', models.CharField(max_length=500)),
                ('option3', models.CharField(max_length=500)),
                ('option4', models.CharField(max_length=500)),
                ('option1_correct', models.BooleanField(default=False)),
                ('option2_correct', models.BooleanField(default=False)),
                ('option3_correct', models.BooleanField(default=False)),
                ('option4_correct', models.BooleanField(default=False)),
                ('timeout', models.PositiveIntegerField()),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Lecture')),
            ],
        ),
    ]
