# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.CharField(default='', max_length=500),
        ),
    ]
