# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20170319_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='lecture',
        ),
    ]
