# Generated by Django 2.0.dev20170223092938 on 2017-03-22 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_questions_lecture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
