# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20170322_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
