# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20170322_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
